## Import the relevent libraries

In [2]:
import pandas as pd
import numpy as np

## Load data

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.shape

(700, 15)

## Create Targets

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
target = np.where(data_preprocessed['Absenteeism Time in Hours'] > data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [7]:
target

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism'] = target

In [9]:
data_preprocessed

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  Absenteeism Time in Hours  month value  \
0            0         2     1                          4            7   
1            0         1     0                          0            7   
2            0         0     0                          2            7   
3            0         2     0                          4            7   
4            0         2     1                          2            7   
..         ...       ...   ...                        ...          ...   
695          1         2     0                          8            5   
696          0         1     2                          3            5   
697          1         0     0                          8            5   
698          1         0     0                          2            5   
699          0         1     1                          2            5   

     Day of week  Excessive Absenteeism  
0              1                      1  
1              1                      0  
2              2                      0  
3              3                      1  
4              3                      0  
..           ...                    ...  
695            2                      1  
696            2                      0  
697            3                      1  
698            3                      0  
699            3                      0  

[700 rows x 16 columns]

## A Comment on targets

In [10]:
target.sum()/target.shape[0]

0.45571428571428574

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [12]:
data_with_targets is data_preprocessed

False

In [13]:
data_with_targets.head()

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0         0         0         0         1                     289   
1         0         0         0         0                     118   
2         0         0         0         1                     179   
3         1         0         0         0                     279   
4         0         0         0         1                     289   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                36   33                  239.554               30          0   
1                13   50                  239.554               31          0   
2                51   38                  239.554               31          0   
3                 5   39                  239.554               24          0   
4                36   33                  239.554               30          0   

   Children  Pets  month value  Day of week  Excessive Absenteeism  
0         2     1            7            1                      1  
1         1     0            7            1                      0  
2         0     0            7            2                      0  
3         2     0            7            3                      1  
4         2     1            7            3                      0

## Select the inputs for the regression

In [14]:
data_with_targets.shape

(700, 15)

In [15]:
data_with_targets.iloc[:,:14]

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0           0         0         0         1                     289   
1           0         0         0         0                     118   
2           0         0         0         1                     179   
3           1         0         0         0                     279   
4           0         0         0         1                     289   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0                     179   
696         1         0         0         0                     225   
697         1         0         0         0                     330   
698         0         0         0         1                     235   
699         0         0         0         1                     291   

     Distance to Work  Age  Daily Work Load Average  Body Mass Index  \
0                  36   33                  239.554               30   
1                  13   50                  239.554               31   
2                  51   38                  239.554               31   
3                   5   39                  239.554               24   
4                  36   33                  239.554               30   
..                ...  ...                      ...              ...   
695                22   40                  237.656               22   
696                26   28                  237.656               24   
697                16   28                  237.656               25   
698                16   32                  237.656               25   
699                31   40                  237.656               25   

     Education  Children  Pets  month value  Day of week  
0            0         2     1            7            1  
1            0         1     0            7            1  
2            0         0     0            7            2  
3            0         2     0            7            3  
4            0         2     1            7            3  
..         ...       ...   ...          ...          ...  
695          1         2     0            5            2  
696          0         1     2            5            2  
697          1         0     0            5            3  
698          1         0     0            5            3  
699          0         1     1            5            3  

[700 rows x 14 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the Data

In [17]:
# from sklearn.preprocessing import StandardScaler

# absenteesize_scaler = StandardScaler()

In [18]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [20]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'month value', 'Day of week'], dtype=object)

In [21]:
columns_to_scale = [ 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'month value', 'Day of week']

In [22]:
absenteesize_scaler = CustomScaler(columns_to_scale)

In [23]:
absenteesize_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Transportation Expense', 'Distance to Work', 'Age',
                      'Daily Work Load Average', 'Body Mass Index', 'Education',
                      'Children', 'Pets', 'month value', 'Day of week'],
             copy=None, with_mean=None, with_std=None)

In [24]:
scaled_inputs =  absenteesize_scaler.transform(unscaled_inputs)

In [25]:
scaled_inputs

reason_1  reason_2  reason_3  reason_4  Transportation Expense  \
0           0         0         0         1                1.005844   
1           0         0         0         0               -1.574681   
2           0         0         0         1               -0.654143   
3           1         0         0         0                0.854936   
4           0         0         0         1                1.005844   
..        ...       ...       ...       ...                     ...   
695         1         0         0         0               -0.654143   
696         1         0         0         0                0.040034   
697         1         0         0         0                1.624567   
698         0         0         0         1                0.190942   
699         0         0         0         1                1.036026   

     Distance to Work       Age  Daily Work Load Average  Body Mass Index  \
0            0.412816 -0.536062                -0.806331         0.767431   
1           -1.141882  2.130803                -0.806331         1.002633   
2            1.426749  0.248310                -0.806331         1.002633   
3           -1.682647  0.405184                -0.806331        -0.643782   
4            0.412816 -0.536062                -0.806331         0.767431   
..                ...       ...                      ...              ...   
695         -0.533522  0.562059                -0.853789        -1.114186   
696         -0.263140 -1.320435                -0.853789        -0.643782   
697         -0.939096 -1.320435                -0.853789        -0.408580   
698         -0.939096 -0.692937                -0.853789        -0.408580   
699          0.074838  0.562059                -0.853789        -0.408580   

     Education  Children      Pets  month value  Day of week  
0    -0.447980  0.880469  0.268487     0.030796    -0.800950  
1    -0.447980 -0.019280 -0.589690     0.030796    -0.800950  
2    -0.447980 -0.919030 -0.589690     0.030796    -0.232900  
3    -0.447980  0.880469 -0.589690     0.030796     0.335149  
4    -0.447980  0.880469  0.268487     0.030796     0.335149  
..         ...       ...       ...          ...          ...  
695   2.232242  0.880469 -0.589690    -0.568019    -0.232900  
696  -0.447980 -0.019280  1.126663    -0.568019    -0.232900  
697   2.232242 -0.919030 -0.589690    -0.568019     0.335149  
698   2.232242 -0.919030 -0.589690    -0.568019     0.335149  
699  -0.447980 -0.019280  0.268487    -0.568019     0.335149  

[700 rows x 14 columns]

In [26]:
scaled_inputs.shape

(700, 14)

## Split the data into train & test shuffle

### import the relevent module

In [27]:
from sklearn.model_selection import train_test_split

### Split

In [28]:
x_train,x_test,y_train,y_test = train_test_split(scaled_inputs,target,train_size = 0.8)

In [29]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [30]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


## Logistic regression with sklearn

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [32]:

reg = LogisticRegression()

In [33]:
reg.fit(x_train,y_train)

C:\Users\nimis\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
reg.score(x_train,y_train)

0.7625

## Manually check the accuracy

In [35]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,

In [36]:
y_train

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,

In [37]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False,  True,
        True,  True,  True,  True, False, False, False, False, False,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True,  True,  True, False,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False,  True,  True, False,  True,  True,
        True, False,  True, False, False, False,  True,  True, False,
       False,  True,  True,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,

In [38]:
np.sum((model_outputs==y_train))

427

In [39]:
model_outputs.shape[0]

560

In [40]:
np.sum((model_outputs==y_train))/model_outputs.shape[0]

0.7625

## Finding the intercept and coefficients

In [41]:
reg.intercept_

array([-0.59255264])

In [42]:
reg.coef_

array([[ 1.96718532, -0.02981542,  2.00982343, -0.43748423,  0.58093951,
        -0.01628655, -0.26916807, -0.03201344,  0.28530859, -0.09864305,
         0.43627017, -0.32043406,  0.01338241, -0.11681004]])

In [43]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'month value', 'Day of week'], dtype=object)

In [44]:
feature_name = unscaled_inputs.columns.values

In [45]:
summary_table = pd.DataFrame(columns=['Feature Name'],data=feature_name)
summary_table['Coefficient']=np.transpose(reg.coef_)

In [46]:
summary_table

Feature Name  Coefficient
0                  reason_1     1.967185
1                  reason_2    -0.029815
2                  reason_3     2.009823
3                  reason_4    -0.437484
4    Transportation Expense     0.580940
5          Distance to Work    -0.016287
6                       Age    -0.269168
7   Daily Work Load Average    -0.032013
8           Body Mass Index     0.285309
9                 Education    -0.098643
10                 Children     0.436270
11                     Pets    -0.320434
12              month value     0.013382
13              Day of week    -0.116810

In [47]:
summary_table.index = summary_table.index +1
summary_table.loc[0] = ['Intercept',reg.intercept_[0]]

In [48]:
summary_table

Feature Name  Coefficient
1                  reason_1     1.967185
2                  reason_2    -0.029815
3                  reason_3     2.009823
4                  reason_4    -0.437484
5    Transportation Expense     0.580940
6          Distance to Work    -0.016287
7                       Age    -0.269168
8   Daily Work Load Average    -0.032013
9           Body Mass Index     0.285309
10                Education    -0.098643
11                 Children     0.436270
12                     Pets    -0.320434
13              month value     0.013382
14              Day of week    -0.116810
0                 Intercept    -0.592553

## Interpreating the coefficients

In [49]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)

In [50]:
summary_table.sort_values('Odds Ratio')

Feature Name  Coefficient  Odds Ratio
0                 Intercept    -0.592553    0.552914
4                  reason_4    -0.437484    0.645659
12                     Pets    -0.320434    0.725834
7                       Age    -0.269168    0.764015
14              Day of week    -0.116810    0.889754
10                Education    -0.098643    0.906066
8   Daily Work Load Average    -0.032013    0.968494
2                  reason_2    -0.029815    0.970625
6          Distance to Work    -0.016287    0.983845
13              month value     0.013382    1.013472
9           Body Mass Index     0.285309    1.330172
11                 Children     0.436270    1.546927
5    Transportation Expense     0.580940    1.787717
1                  reason_1     1.967185    7.150522
3                  reason_3     2.009823    7.462000

## Testing the model

In [51]:
reg.score(x_test,y_test)

0.6928571428571428

In [52]:
predict_proba = reg.predict_proba(x_test)

In [54]:
predict_proba.shape

(140, 2)

## save the model

In [55]:
import pickle

In [56]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [57]:
with open('scaler','wb') as file:
    pickle.dump(absenteesize_scaler,file)